# -*- coding: utf-8 -*-
"""part3_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUlht-lQMcpxaLp9vvqMOPyox6Fd-2Pt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.decomposition import PCA

# Load the cleaned dataset
df = pd.read_csv("clean_adult_data.csv")

# Remove target variable for clustering
X = df.drop("income", axis=1)

# Dimensionality reduction with PCA for visualization (keeping 2 dimensions)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# Clustering with K-Means
kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
df["kmeans_cluster"] = kmeans.fit_predict(X)

# Clustering with Hierarchical Clustering
hierarchical = AgglomerativeClustering(n_clusters=2)
df["hierarchical_cluster"] = hierarchical.fit_predict(X)

# Evaluation of clusters with Silhouette Score
kmeans_silhouette = silhouette_score(X, df["kmeans_cluster"])
hierarchical_silhouette = silhouette_score(X, df["hierarchical_cluster"])

print("Silhouette Score for K-Means:", kmeans_silhouette)
print("Silhouette Score for Hierarchical Clustering:", hierarchical_silhouette)

# Visualization of results with Scatter Plot (after PCA)
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=df["kmeans_cluster"], palette="Set1")
plt.title("K-Means Clustering after PCA")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.subplot(1, 2, 2)
sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=df["hierarchical_cluster"], palette="Set2")
plt.title("Hierarchical Clustering after PCA")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.show()

# Visualization of Dendrogram for Hierarchical Clustering
plt.figure(figsize=(12, 5))
linkage_matrix = linkage(X, method="ward")
dendrogram(linkage_matrix)
plt.title("Hierarchical Clustering Dendrogram")
plt.xlabel("Samples")
plt.ylabel("Cluster Distance")
plt.show()