# -*- coding: utf-8 -*-
"""part1_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ijRggEvVyiDgWuTI9zkRW7b61yzhhSm3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.decomposition import PCA

# Load dataset
file_path = "adult.data"
columns = ["age", "workclass", "fnlwgt", "education", "education-num", "marital-status",
           "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss",
           "hours-per-week", "native-country", "income"]

# Read the dataset
df = pd.read_csv(file_path, names=columns, na_values=" ?")

print(df.info())
print(df.head())

# Check for missing values
missing_values = df.isnull().sum()
print("Missing Values per Column:\n", missing_values)

# Replace missing values with the most frequent value (mode)
for col in df.columns:
    if df[col].isnull().sum() > 0:
        df[col].fillna(df[col].mode()[0], inplace=True)

# Encode categorical features
label_encoders = {}
for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Normalize numerical features
scaler = MinMaxScaler()
numeric_columns = ["age", "fnlwgt", "education-num", "capital-gain", "capital-loss", "hours-per-week"]
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

# PCA for dimensionality reduction (keeping 95% of variance)
pca = PCA(n_components=0.95)
pca_transformed = pca.fit_transform(df.drop("income", axis=1))
print("Explained variance ratio:", pca.explained_variance_ratio_)

# Save the cleaned dataset
df.to_csv("clean_adult_data.csv", index=False)