# -*- coding: utf-8 -*-
"""part2_feature_selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xo9e-cK_Rj-v2cMxhymz3tMCIWwnu0Ry
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
import time

# Load the cleaned dataset
df = pd.read_csv("clean_adult_data.csv")

# Split features and target variable
X = df.drop("income", axis=1)
y = df["income"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Correlation Analysis (Heatmap)
plt.figure(figsize=(12, 6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Feature Correlation Matrix")
plt.show()

# Feature Selection with SelectKBest (ANOVA F-value)
k_best = SelectKBest(score_func=f_classif, k=5)
k_best.fit(X, y)
selected_features = X.columns[k_best.get_support()]
print("Top 5 features according to SelectKBest:", selected_features)

# Feature Selection with Feature Importance from Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X, y)
importances = rf.feature_importances_
importance_df = pd.DataFrame({"Feature": X.columns, "Importance": importances})
importance_df = importance_df.sort_values(by="Importance", ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x="Importance", y="Feature", data=importance_df, palette="viridis")
plt.title("Feature Importance from Random Forest")
plt.show()

start_time = time.time()
dt_full = DecisionTreeClassifier(random_state=42)
dt_full.fit(X_train, y_train)
train_accuracy_full = dt_full.score(X_train, y_train)
test_accuracy_full = dt_full.score(X_test, y_test)
time_full = time.time() - start_time
print("\nResults with all features:")
print(f"Train Accuracy: {train_accuracy_full:.4f}")
print(f"Test Accuracy: {test_accuracy_full:.4f}")
print(f"Training Time: {time_full:.4f} seconds")

# Select top 5 most important features
top_features = importance_df['Feature'].head(5)

# Create X_train_selected and X_test_selected with selected features
X_train_selected = X_train[top_features]
X_test_selected = X_test[top_features]

start_time = time.time()
dt_selected = DecisionTreeClassifier(random_state=42)
dt_selected.fit(X_train_selected, y_train)
train_accuracy_selected = dt_selected.score(X_train_selected, y_train)
test_accuracy_selected = dt_selected.score(X_test_selected, y_test)
time_selected = time.time() - start_time

print("\nResults with top 5 features:")
print(f"Train Accuracy: {train_accuracy_selected:.4f}")
print(f"Test Accuracy: {test_accuracy_selected:.4f}")
print(f"Training Time: {time_selected:.4f} seconds")

# Outlier Detection with Z-score
z_scores = np.abs(stats.zscore(df.select_dtypes(include=[np.number])))
outliers_z = (z_scores > 3).sum(axis=0)
print("Outliers per feature according to Z-score:\n", outliers_z)

# Outlier Visualization with Boxplot
plt.figure(figsize=(12, 6))
sns.boxplot(data=df.select_dtypes(include=[np.number]))
plt.xticks(rotation=45)
plt.title("Boxplot for outlier detection")
plt.show()